// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['backend']['App']['CheckUpdate']();
}

export function Connect(arg1) {
  return window['go']['backend']['App']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['backend']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['backend']['App']['Disconnect']();
}

export function GenerateReport(arg1) {
  return window['go']['backend']['App']['GenerateReport'](arg1);
}

export function GetAutoStart() {
  return window['go']['backend']['App']['GetAutoStart']();
}

export function GetObfsAccepted() {
  return window['go']['backend']['App']['GetObfsAccepted']();
}

export function GetObfsMode() {
  return window['go']['backend']['App']['GetObfsMode']();
}

export function GetProfile(arg1) {
  return window['go']['backend']['App']['GetProfile'](arg1);
}

export function GetVersion() {
  return window['go']['backend']['App']['GetVersion']();
}

export function IsRunning() {
  return window['go']['backend']['App']['IsRunning']();
}

export function ListProfiles() {
  return window['go']['backend']['App']['ListProfiles']();
}

export function SaveProfile(arg1, arg2) {
  return window['go']['backend']['App']['SaveProfile'](arg1, arg2);
}

export function SetAutoStart(arg1) {
  return window['go']['backend']['App']['SetAutoStart'](arg1);
}

export function SetObfsAccepted(arg1) {
  return window['go']['backend']['App']['SetObfsAccepted'](arg1);
}

export function SetObfsMode(arg1) {
  return window['go']['backend']['App']['SetObfsMode'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}

export function CheckExclude(arg1) {
  return window['go']['backend']['App']['CheckExclude'](arg1);
}

export function GetExcludes() {
  return window['go']['backend']['App']['GetExcludes']();
}

export function SetExcludes(arg1) {
  return window['go']['backend']['App']['SetExcludes'](arg1);
}

export function GetRussiaDirect() {
  return window['go']['backend']['App']['GetRussiaDirect']();
}

export function SetRussiaDirect(arg1) {
  return window['go']['backend']['App']['SetRussiaDirect'](arg1);
}

export function InstallUpdate() {
  return window['go']['backend']['App']['InstallUpdate']();
}

export function SaveLogs() {
  return window['go']['backend']['App']['SaveLogs']();
}
