// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function CheckUpdate():Promise<backend.UpdateInfo>;

export function Connect(arg1:backend.ConnectParams):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GenerateReport(arg1:Array<backend.LogEntry>):Promise<string>;

export function GetAutoStart():Promise<boolean>;

export function GetObfsAccepted():Promise<boolean>;

export function GetObfsMode():Promise<string>;

export function GetProfile(arg1:string):Promise<backend.ProfileData>;

export function GetVersion():Promise<string>;

export function IsRunning():Promise<boolean>;

export function ListProfiles():Promise<Record<string, backend.ProfileData>>;

export function SaveProfile(arg1:string,arg2:backend.ProfileData):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetObfsAccepted(arg1:boolean):Promise<void>;

export function SetObfsMode(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function CheckExclude(arg1:string):Promise<string>;

export function GetExcludes():Promise<Array<backend.ExcludeEntry>>;

export function SetExcludes(arg1:Array<backend.ExcludeEntry>):Promise<Array<backend.ExcludeEntry>>;

export function GetRussiaDirect():Promise<backend.RussiaInfo>;

export function SetRussiaDirect(arg1:boolean):Promise<backend.RussiaInfo>;

export function InstallUpdate():Promise<void>;
